services:
  - type: web
    name: wikichat
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    startCommand: |
      chainlit run backend_server.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CHAINLITE_CONFIG
        value: llm_config.yaml
      - key: COSMOS_CONNECTION_STRING
        sync: false
